In [2]:
import bs4
import requests
import json
import pandas as pd
import numpy as np
import time
import os
from IPython.display import clear_output
from urllib.request import urlopen

In [3]:
# 요청 함수
def getSource(site) :
    # 헤더 정보
    header_info = {
        'User-Agent' : 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.146 Safari/537.36'
    }
    
    # 요청한다.
    response = requests.get(site, headers = header_info)
    # print(response.text)
    
    # json 객체 생성
    obj = json.loads(response.text)
    return obj

In [20]:
# 한 횟차의 데이터를 추출한다.
def getData(obj) :
    #print(obj['drwNoDate'])
    #print(obj['drwtNo1'])
    #print(obj['drwtNo2'])
    #print(obj['drwtNo3'])
    #print(obj['drwtNo4'])
    #print(obj['drwtNo5'])
    #print(obj['drwtNo6'])
    #print(obj['bnusNo'])
    data_dict = {
        '추첨날짜' : [obj['drwNoDate']],
        '번호1' : [obj['drwtNo1']],
        '번호2' : [obj['drwtNo2']],
        '번호3' : [obj['drwtNo3']],
        '번호4' : [obj['drwtNo4']],
        '번호5' : [obj['drwtNo5']],
        '번호6' : [obj['drwtNo6']],
        '보너스번호' : [obj['bnusNo']]
    }
    
        
    # 데이터 프레임 생성
    df1= pd.DataFrame(data_dict)
    if os.path.exists('data5.csv') == False :
        # 파일이 없을 경우
        df1.to_csv('data5.csv', encoding='utf-8-sig', index=False)
    else :
        df1.to_csv('data5.csv',encoding='utf-8-sig' , index=False, header = False, mode='a')

In [21]:
# 현재 회차를 수집 할 것인지.
def getNext(obj) :
    if obj['returnValue'] == 'success' :
        return True
    else:
        return False

In [23]:
drwNo = 1

while True : 
    time.sleep(1)
    clear_output(wait=True)
    
    site = f'https://www.dhlottery.co.kr/common.do?method=getLottoNumber&drwNo={drwNo}'

    obj = getSource(site)
    
    # 현재 회차를 수집할 것인지..
    chk = getNext(obj)
    
    if chk == True:
        print(f'{drwNo}회차 수집')
        getData(obj)
        drwNo = drwNo + 1
    else :
        print('수집완료')
        break

수집완료

In [24]:
df = pd.read_csv('data5.csv')
df

           추첨날짜  번호1  번호2  번호3  번호4  번호5  번호6  보너스번호
0    2002-12-07   10   23   29   33   37   40     16
1    2002-12-14    9   13   21   25   32   42      2
2    2002-12-21   11   16   19   21   27   31     30
3    2002-12-28   14   27   30   31   40   42      2
4    2003-01-04   16   24   29   40   41   42      3
..          ...  ...  ...  ...  ...  ...  ...    ...
943  2021-01-02    2   13   16   19   32   33     42
944  2021-01-09    9   10   15   30   33   37     26
945  2021-01-16    9   18   19   30   34   40     20
946  2021-01-23    3    8   17   20   27   35     26
947  2021-01-30   13   18   30   31   38   41      5

[948 rows x 8 columns]

In [32]:
df2 = df.iloc[:,1:8]